
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.1 EDK_MS1.53d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xsysace.h"

/*
* The configuration table for devices
*/

XSysAce_Config XSysAce_ConfigTable[] =
{
	{
		XPAR_SYSACE_COMPACTFLASH_DEVICE_ID,
		XPAR_SYSACE_COMPACTFLASH_BASEADDR
	}
};


